version: "3.9"

services:
  rt:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    depends_on:
      - db
    #deploy:
      #mode: replicated
      #replicas: 5
    volumes:
      - /opt/rt/RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - /opt/rt/msmtp/msmtp.conf:/etc/msmtprc:ro
      - /opt/rt/msmtp:/msmtp:ro
      - /opt/rt/getmail/getmailrc:/getmail/getmailrc:ro
      - /opt/rt/gpg:/opt/rt5/var/data/gpg
      - /opt/rt/smime:/opt/rt5/var/data/smime
      - /opt/rt/shredder:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
      - /opt/rt/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - rt

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "rt"
      POSTGRES_PASSWORD: "rtdbpwd"
      POSTGRES_USER: "rt"
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /opt/rt/db:/var/lib/postgresql/data
    networks:
      - rt

  cron:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    # the cron daemon needs to run as root
    user: root
    command: [ "/root/cron_entrypoint.sh" ]
    depends_on:
      - rt
      - nginx
    volumes:
      - /opt/rt/RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - /opt/rt/msmtp/msmtp.conf:/etc/msmtprc:ro
      - /opt/rt/msmtp:/msmtp:ro
      - /opt/rt/getmail/getmailrc:/getmail/getmailrc:ro
      - /opt/rt/gpg:/opt/rt5/var/data/gpg
      - /opt/rt/smime:/opt/rt5/var/data/smime
      - /opt/rt/crontab:/root/crontab:ro # needed so we can add it ro. Permissions are changed in startup script
      - /opt/rt/cron:/cron
      - /opt/rt/shredder:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rt

  nginx:
    build:
      context: nginx
    image: firefart/requesttracker:nginx-latest
    depends_on:
      - rt
      - pgadmin
    volumes:
      - /opt/rt/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/rt/nginx/certs:/certs/:ro
      - /opt/rt/nginx/startup-scripts:/docker-entrypoint.d/:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rt


  pgadmin:
    image: dpage/pgadmin4:latest
    profiles:
      - full
    restart: always
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@root.com}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_DISABLE_POSTFIX: disable
    secrets:
      - pgadmin_password
    volumes:
      - /opt/rt/pgadmin:/var/lib/pgadmin
    networks:
      - rt

secrets:
  pgadmin_password:
    file: /opt/rt/pgadmin_password.secret

volumes:
  vol_pgadmin: {}

networks:
  rt:

